### ISSUE TITLE
About the counterfactual 

### ISSUE THREAD

**Issue by BoomShakaY** [raoyongming/CAL#16]
Hi, I read your paper and got some new experiences; I have a question about counterfactual attention, where you use random attention sampled from a uniform distribution U(0, 2). I wonder why not sampling from the **Gaussian distribution** from ubiquitous and intuitive considerations?  Or is there a reference for this design?

**Comment by BoomShakaY** [comment]
@raoyongming

**Comment by raoyongming** [comment]
Hi @BoomShakaY, the real attention is generated by a conv layer with BN and ReLU ([BasicConv2D](https://github.com/raoyongming/CAL/blob/0ba9d5084f2532eeb21c9ef051c23f8b339595ff/fgvc/models/inception.py#L374)). We try to make sure the distribution of the counterfactual attention is close to the real attention. Since we find the attention value of the baseline model is usually smaller than 2, the attention values are sampled from U(0,2). I think a more carefully designed counterfactual attention may be better, but our design can already achieve good performance.
