### ISSUE TITLE
Reproduce Result for MSMT dataset 

### ISSUE THREAD

**Issue by petertran1811** [raoyongming/CAL#8]
I am trying to reproduce the result as shown in the paper for the MSMT which is mAP@64% and R1@84.2%; however, I could not do it. May I ask about the backbone you are using to get these results? Is it the same with the code in your repository or do you use different approach? And do you take the best case during training or the result after training for the whole 160 epoch? I am sorry if these questions bother you. Thank in advance!

**Comment by CHENGY12** [comment]
Hi, thanks for your attention to our method. The backbone and method we using in this repo are the same as the paper. We only test the final checkpoint on MSMT，because the inference cost on MSMT is large.  

We release the model on MSMT in [Google Drive](https://drive.google.com/drive/folders/17hu8Lpva8oJAlmb8ndja14vwo22waiL4?usp=sharing). Hope you find it helpful.
To use this model, you can download the "inception.py" from Google Drive and put it in the ```/reid/modeling/backbones/``` , then add the code ``` from .backbones.inception import BasicConv2d ``` in  ```/reid/modeling/baseline.py``` .
It is because we removed the inception.py and add BasicConv2d in baseline.py to clean the code.

We checked and trained the model with the code in this repo for MSMT17 2 months ago, and get similar performance as the paper reported.
![1](https://user-images.githubusercontent.com/17920133/142433892-cdea95f0-bdea-425c-83f6-1fc995258e0f.png)
![2](https://user-images.githubusercontent.com/17920133/142433928-c6184110-1287-4c30-94e0-5b27fc6d336c.jpg)

Please feel free to connect with us if you have any questions about reproducing on MSMT.

**Comment by CHENGY12** [comment]
Hi, thanks for your attention to our method. The backbone and method we using in this repo are the same as the paper. We only test the final checkpoint on MSMT，because the inference cost on MSMT is large.  We release the model on MSMT. Please refer to [issue  6](https://github.com/raoyongming/CAL/issues/6)

We checked and trained the model with the code in this repo for MSMT17 2 months ago, and get similar performance as the paper reported.
![1](https://user-images.githubusercontent.com/17920133/142433892-cdea95f0-bdea-425c-83f6-1fc995258e0f.png)
![2](https://user-images.githubusercontent.com/17920133/142433928-c6184110-1287-4c30-94e0-5b27fc6d336c.jpg)

Please feel free to connect with us if you have any questions about reproducing on MSMT.

**Comment by petertran1811** [comment]
> Hi, thanks for your attention to our method. The backbone and method we using in this repo are the same as the paper. We only test the final checkpoint on MSMT，because the inference cost on MSMT is large. We release the model on MSMT. Please refer to [issue 6](https://github.com/raoyongming/CAL/issues/6)
> 
> We checked and trained the model with the code in this repo for MSMT17 2 months ago, and get similar performance as the paper reported. ![1](https://user-images.githubusercontent.com/17920133/142433892-cdea95f0-bdea-425c-83f6-1fc995258e0f.png) ![2](https://user-images.githubusercontent.com/17920133/142433928-c6184110-1287-4c30-94e0-5b27fc6d336c.jpg)
> 
> Please feel free to connect with us if you have any questions about reproducing on MSMT.

OMG! It was a quick reply. You are so kind-hearted. Thank you so much. I understand now and will try to understand your outstanding idea
